#!/bin/bash
usage()
{
    echo "usage: learndownloader [-d <output_dir>] \"curl_command\""
    echo "  -d  directory to save files to"
    echo "  -h  shows this message and exit"
}

while getopts 'd:h' option; do
    case $option in
		d)      dir=$OPTARG
                ;;
        h)      usage
                exit
                ;;
        \?)     usage
                exit 1
    esac
    shift
done

mkdir -p $HOME/.cache/learndownloader
cachedir="$HOME/.cache/learndownloader"
openssl_conf="$HOME/.config/learndownloader/openssl.conf"
curl_command="${@: -1}"

if [ -z "$curl_command" ]
then
    usage
    exit 1
fi

if [ ! -z "$dir" ]
then
    mkdir -p $dir
    if [ $? -ne 0 ]
    then
        exit 1
    fi
fi

echo "Getting HTML page..."
bash -c "OPENSSL_CONF=$openssl_conf $curl_command -s --compressed" > $cachedir/tmp.html

cookies=$(echo "$curl_command" | grep -oP "\-H 'Cookie:.*?'")
useragent=$(echo "$curl_command" | grep -oP "\-H 'User-Agent:.*?'")
echo -n "" > $cachedir/finalurls.txt

echo "Retrieving urls..."
grep -o 'href=\"https:\/\/learn\.univpm\.it\/mod\/resource\/view\.php?id\=[0-9]*\"' $cachedir/tmp.html | sed 's/href=//' | tr -d '"' > $cachedir/urls.txt
grep -oP 'href=\"https:\/\/learn\.univpm\.it\/pluginfile\.php\/[0-9]{6}/course\/section\/[0-9]{6}\/.*?\.pdf\"' $cachedir/tmp.html | sed 's/href=//' | tr -d '"' >> $cachedir/finalurls.txt

while read url; do
	bash -c "OPENSSL_CONF=$openssl_conf curl $url $cookies $useragent -kIs -w %{redirect_url} -o /dev/null" >> $cachedir/finalurls.txt
	echo "" >> $cachedir/finalurls.txt
done < "$cachedir/urls.txt"

echo "Downloading files..."
count=0

while read finalurl; do
	filename=$(echo "$finalurl" | sed "s/^.*\///" | sed "s/%20/_/g" | sed "s/\?.*$//")
    if [ ! -z "$dir" ]
    then
        filename="$dir/$filename"
    fi
    
    if test -f "$filename"; then
        echo "Skipped: $filename already exists"
        continue
    fi


	bash -c "OPENSSL_CONF=$openssl_conf curl -s $finalurl $cookies $useragent -o $filename"
    echo "Downloaded: $filename"
	count=$((count+1))
done < "$cachedir/finalurls.txt"

echo "$count file downloaded."
exit 0
